### PR TITLE
Add felt_div

### PR DESCRIPTION
**Pull request by edg-l**
Adds support for felt division

`a * b^-1 % prime`

I made the inverse from this rusty pseudocode:

```rust
pub fn inverse(&self) -> Self {
        let (mut t, mut new_t) = (0, 1);
        let (mut r, mut new_r) = (FieldElement::k_modulus(), self.0);
        while new_r != 0 {
            let quotient = r / new_r;
            (t, new_t) = (new_t, t - (quotient * new_t));
            (r, new_r) = (new_r, r - quotient * new_r);
        }
        assert!(r == 1);
        FieldElement::new(t)
}
```

Need to figure out how to add tests and then I'll do so soon.

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Currently felt_div libfunc is not implemented.

Issue Number: N/A

# What is the new behavior?

The felt_div libfunc is implemented.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

Feel free to tell me any errors or issues and I'll fix them asap.

## Example IR generated

```llvm
define i252 @felt_div(i252 %0, i252 %1) {
entry:
  %t = alloca i503, align 8
  %new_t = alloca i503, align 8
  %r = alloca i503, align 8
  %new_r = alloca i503, align 8
  store i503 0, ptr %t, align 4
  store i503 1, ptr %new_t, align 4
  store i503 3618502788666131213697322783095070105623107215331596699973092056135872020481, ptr %r, align 4
  %new_r_extended = sext i252 %1 to i503
  store i503 %new_r_extended, ptr %new_r, align 4
  br label %while

while:                                            ; preds = %body, %entry
  %new_r_value = load i503, ptr %new_r, align 4
  %while_compare = icmp ne i503 %new_r_value, 0
  br i1 %while_compare, label %body, label %exit

body:                                             ; preds = %while
  %r_value = load i503, ptr %r, align 4
  %new_r_value1 = load i503, ptr %new_r, align 4
  %new_quotient_value = sdiv i503 %r_value, %new_r_value1
  %old_t_value = load i503, ptr %t, align 4
  %new_t_value = load i503, ptr %new_t, align 4
  store i503 %new_t_value, ptr %t, align 4
  %quotient_mul_new_t = mul i503 %new_quotient_value, %new_t_value
  %sub_t_res = sub i503 %old_t_value, %quotient_mul_new_t
  store i503 %sub_t_res, ptr %new_t, align 4
  %old_r_value = load i503, ptr %r, align 4
  %new_r_value2 = load i503, ptr %new_r, align 4
  store i503 %new_r_value2, ptr %r, align 4
  %quotient_mul_new_r = mul i503 %new_quotient_value, %new_r_value2
  %sub_r_res = sub i503 %old_r_value, %quotient_mul_new_r
  store i503 %sub_r_res, ptr %new_r, align 4
  br label %while

exit:                                             ; preds = %while
  %extended_a = sext i252 %0 to i503
  %inverse = load i503, ptr %t, align 4
  %res = mul i503 %extended_a, %inverse
  %res3 = call i252 @modulo(i503 %res)
  ret i252 %res3
}
```

### CODE REVIEW

**Review by abdelhamidbakhta — COMMENTED** [review]
lgtm. Once the feature is tested we can merge it.

**Review by LucasLvy — CHANGES_REQUESTED** [review]
could you add a test for it plz. Something simple for now (something like the addition)

**Comment by edg-l** [comment]
Status: felt_div is not supported yet by the cairo to sierra compiler ([here](https://github.com/starkware-libs/cairo/blob/1991669a0453bd65541ff81a12772bac05130052/crates/cairo-lang-sierra/src/simulation/core.rs#L915))

will see to make the sierra code myself

**Comment by edg-l** [comment]
I added the test, but it is for compilation only, there is actually a bug since i dont get correct results from the division, i.e 6 / 2 returns 2 right now.

**Comment by LucasLvy** [comment]
Is it fixed ?

**Comment by edg-l** [comment]
> Is it fixed ?

Not yet, but I guess you can merge this and I can fix it on another pr when i find the solution. I don't have much idea right now as to why happens, I thought maybe we need to do a floor division for the quotient.

**Comment by LucasLvy** [comment]
I'd rather not merge something we know is not working. But I'll TAL at this to see if I have any idea

**Pull request merged**
